version: '3.9'

services:
  web:
    image: meal-genius-full-azure-speed-optimised
    container_name: meal-genius
    ports:
      - 8080:5139
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mealGeniusDb;Username=ayoub;Password=REDACTED
      - OPENAI_API_KEY= REDACTED
      - REACT_APP_API_BASE_URL=http://localhost:8080