using FluentEmail.Core;
using MealGeniusBackend.DataAcess;
using MealGeniusBackend.Helpers;
using MealGeniusBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using OpenAI_API;
using Stripe;
using System.Text;
// OpenAI_API.Models.Model.GPT4


namespace MealGeniusBackend.Services.Dashboard
{
    public interface IMealPlanService
    {
        Task GenerateMealPlan(UserTaskDTO userTaskDTO);
    }



    public class MealPlanService : IMealPlanService
    {
        private readonly List<string> mealBackgroundcolors = new List<string>
        {
            "#F0EBFB", "#EEFBEB", "#E8EEF9", "#F4EAFA", "#E6FAF9",
            "#EBEEF8", "#EAF6F6", "#EAEBF6", "#F9E9F2", "#FDEAE7",
            "#F2EBF9", "#E9F5F9", "#F6EBFC", "#EDFEE8", "#F5EAFD",
            "#E9FBFD", "#FAF7EE", "#E8F6F1", "#FBE8FB", "#F9FCE7"
        };
        private readonly Random random = new Random();
        private readonly UserDbContext _dbContext;
        private readonly ILogger<MealPlanService> _logger;
        private readonly IOpenAIService _openAIService;
        private readonly IAzureBlobService _azureBlobService;
        public MealPlanService(UserDbContext userDbContext, ILogger<MealPlanService> logger, IOpenAIService openAIService, IAzureBlobService azureBlobService)
        {
            _dbContext = userDbContext;
            _logger = logger;
            _openAIService = openAIService;
            _azureBlobService = azureBlobService;
        }
        public async Task GenerateMealPlan(UserTaskDTO userTaskDTO)
        {
            var userTask = _dbContext.Tasks.Where(u => u.Id == userTaskDTO.Id).FirstOrDefault();

            try
            {
                userTask.MealsGenerationExcecutedAt = DateTime.UtcNow;
                await _dbContext.SaveChangesAsync();
                // Logic for generating a user dashboard
                var userInput = _dbContext.UserInputs
                              .Where(u => u.TaskId == userTaskDTO.Id)
                              .FirstOrDefault();
                if (userInput is null || userInput.UserData is null)
                {
                    _logger.LogError("UserInput not found");
                    return;
                }

                var existingMealPlan = _dbContext.MealPlans.SingleOrDefault(mealPlan => mealPlan.TaskId == userTaskDTO.Id);

                if (existingMealPlan is not null && !existingMealPlan.MealPlanJson.IsNullOrEmpty())
                {
                    if (userTaskDTO.Status == UserTaskStatus.TobeRetried)
                    {
                        _dbContext.MealPlans.Remove(existingMealPlan);
                        await _dbContext.SaveChangesAsync();
                    }
                    else
                    {
                        _logger.LogInformation("Mealplan already exists for this task");
                        return;
                    }
                }


                // Generate First Json that contains the meals PreData
                var timer = new ServiceTaskTimer("MealPlanService", "The generation of : Create 12 personalized meal ideas");
                timer.Start();
                var MealRecipeBreakdow_JsonExamplePath = "JsonFiles/Meal_PreData_Generation.txt";
                string MealRecipeBreakdow_JsonExample = System.IO.File.ReadAllText(MealRecipeBreakdow_JsonExamplePath);



                var userDashboard = _dbContext.UserDashboards.FirstOrDefault(u => u.UserId == userTaskDTO.UserId);
                var Macros = userDashboard.MacroTargets;
                var Micros = userDashboard.MicroGuide;
                var HealthGoals = userDashboard.UserGoalsGuide;
                var kpis = userDashboard.JsonUserKeyInfos;

                var UserInputsJson = userInput.UserData;
                string systemPromptJsonMealsGeneration = $@"You are an AI assistant for MealGenius, an app designed for personalized nutrition and meal planning.
 
                                It focuses on setting nutritional goals and providing tailored meal plans based on user data. 
                                The app caters to a diverse audience, including individuals with ADHD, and emphasizes informative educative content while being friendly, fun.

                                MealGenius is used globally, so please use simple, clear English, avoiding slang or region-specific terms.
                                You can use emojis to add engagement and fun, but only where appropriate. 


                    The user's dashboard informations that was generated by similar GPT AI before is provided in the following JSON format.
                    {kpis}

                    User information relevant informations is provided in the following JSON format.
                    {UserInputsJson}";

                string userPromptJsonMealsGeneration = $@"

                    Create 12 personalized meal ideas, each with a unique blend of attributes. For every meal, include:

                    MealName: Craft a creative and inviting name.
                    MealType: Assign one or more categories (e.g., Breakfast, Lunch, Dinner, Snack, Dessert, Smoothie). A meal can belong to multiple types, like 'Breakfast' and 'Smoothie'.
                    PreparationSkill: Indicate the level of effort and skill required for the recipe, categorized into 'Easy', 'Intermediate', 'Advanced', and 'Expert'. 
                    - 'Easy' implies recipes that are quick and straightforward, requiring basic cooking skills and minimal ingredients. Ideal for beginners or those seeking a quick meal.
                    - 'Intermediate' involves recipes that require some cooking experience, introducing more complex techniques and a greater variety of ingredients, but still accessible to a motivated home cook.
                    - 'Advanced' denotes recipes that demand a good understanding of cooking techniques, involving multiple components, specialized ingredients, or equipment, suitable for those with significant cooking experience.
                    - 'Expert' represents the highest complexity level, requiring extensive culinary knowledge, precision, and patience, often including professional techniques and intricate presentations. 
                    MoodSuitability: Suggest one or more mood categories that will serve as tags for each meal. It's important to ensure that meals share common mood suitability tags to facilitate user exploration of related options. These tags should be imaginative and cater to various user preferences and emotional states (e.g., 'Adventure Seeker', 'Soul Soother', 'Memory Lane', 'Dreamy Indulgence'). By maintaining common mood tags across different meals, 
                    users can easily find meals that match their current mood or desired emotional state, enhancing personalization and user experience. Aim for a mix of moods that cater to a broad range of dietary preferences and emotional needs, ensuring a balanced and diverse meal selection, but ensure that meals share mood suitablity between each other

                    Note: Each filter category (Meal Type, Preparation Type, Mood Suitability) can have multiple options for a single meal to increase flexibility and user discoverability. For instance, a meal can be both a 'Breakfast' and a 'Smoothie', and suit moods like 'Energizing' and 'Refreshing'.
                    Ensure that the meals have common elements for users to explore related options and maintain a balance between creativity, dietary preferences, and culinary diversity.

                    Based on the user data provided, create a JSON structure with 12 wide range personalized meals. Ensure each meal aligns with the user’s preferences, health goals, and lifestyle, reflecting the diversity and balance necessary for their diet.

                    Please propose a wise range of food.
                    Plz follow just the format of the JSON file provided in the following line, don't propose the same meals presented below, be creative and propose a wide range of meals based on the user data provided.

                    {MealRecipeBreakdow_JsonExample}


                    The user's dashboard informations that was generated by similar GPT AI before is provided in the following JSON format.
                    {kpis}

                    User information relevant informations is provided in the following JSON format.
                    {UserInputsJson}   ";
                
                
                
                var userMealsJson = await _openAIService.GenerateJsonBasedOnPromptResponseAsync(systemPromptJsonMealsGeneration, userPromptJsonMealsGeneration, 1000, model: "gpt-4-1106-preview", temperature: 0.8);
                
                
                UserMealsRoot? theUserMealsRoot = JsonConvert.DeserializeObject<UserMealsRoot>(userMealsJson);
                timer.StopAndLog();
                if (theUserMealsRoot is null)
                {
                    _logger.LogError("UserMealsRoot is null");
                    return;
                }
                //Meal Recipe and PostData Generation
                var tasks = new List<Task>();
                var timer1 = new ServiceTaskTimer("MealPlanService", "The generation of 12 meal recipes in a parallele task");
                timer1.Start();
                foreach (var meal in theUserMealsRoot.UserMeals)
                {
                    tasks.Add(FillUserMealsData(meal, UserInputsJson));
                }
                await Task.WhenAll(tasks);
                timer1.StopAndLog();

                string mealPlanJson = JsonConvert.SerializeObject(theUserMealsRoot);



                // If no record exists, create a new one
                MealPlan newMealPlan = new MealPlan
                {
                    Id = Guid.NewGuid(),
                    UserId = userTaskDTO.UserId,
                    TaskId = userTaskDTO.Id,
                    Title = "Sample Meal Plan",
                    MealPlanJson = mealPlanJson,
                    GroceryListJson = "",
                    CreatedAt = DateTime.UtcNow,
                    MealPlanVersion = 1                 
                };

                // Add the new record to the database
                _dbContext.MealPlans.Add(newMealPlan);
                userTask.UserOutputStatus = UserOutputStatus.MealPlanCompleted;

                _dbContext.SaveChanges();
                _logger.LogInformation($"MealPlan generated for UserId: {userTaskDTO.UserId}");
            }

            catch (Exception ex)
            {
                try
                {
                    userTask.Status = UserTaskStatus.Failed;
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException ex1)
                {
                    _logger.LogError(ex1, "Concurrency error while updating UserTask status");
                    // Handle concurrency issue, maybe retry or notify the user
                }
                catch (DbUpdateException ex1)
                {
                    _logger.LogError(ex1, "Database update error while updating UserTask status");
                    // Handle DbUpdateException
                }
                catch (Exception ex1)
                {
                    _logger.LogError(ex1, "Error in the _dbContext while updating UserTask status");
                    throw;
                }
                _logger.LogError(ex, "Error while generating MealPlan");
                throw;
            }
        }
        async Task FillUserMealsData(aMeal meal, string UserInputsJson)
        {
            meal.Tags = new List<string>();

            meal.Tags.AddRange(meal.MealType);
            //meal.Tags.AddRange(meal.MoodSuitability);
            meal.Tags.Add(meal.PreparationSkill);

            meal.Recipe = await GetMealRecipe(meal, UserInputsJson);


            string systemPromptJsonMealDataGeneration = @"You are an AI assistant for MealGenius, an app designed for personalized nutrition and meal planning.
 
It focuses on setting nutritional goals and providing tailored meal plans based on user data. 
The app caters to a diverse audience, including individuals with ADHD, and emphasizes informative educative content while being friendly, fun.";

            string filePath = Path.Combine(Directory.GetCurrentDirectory(), "JsonFiles", "MealTotalBreakDown_JsonExample.json");
            if (!System.IO.File.Exists(filePath))
            {
                throw new FileNotFoundException($"The file {filePath} was not found.");
            }
            string mealTotalBreakDown_JsonExample = System.IO.File.ReadAllText(filePath);

            string userPromptJsonMealBreakdown = $@"
The following is the recipe of the user
[Recipe : {meal.Recipe}]

to make this recipe easy to parse by our C# backend and React app int the front we want to serialize it to a json, can you create this json with the following format :

[JsonFormat : {mealTotalBreakDown_JsonExample} ]

In this json The MealDetails object will provide a quick visual representation of key information as tags and assist in generating grocery lists. 
Meal Name: Specify the name of the dish.

Macronutrient: List each macronutrient (proteins, carbohydrates, fats, and calories) with their respective quantities in grams (g) or calories (kcal), please provide one average value for calories if there is a range.
    In this section it's very important and crucial that you provide the exact value of each macronutrient in the meal and follow this exact format, which will help up to parse the data and display it in the front end app.
    So Please follow this format :
    ""Macronutrients"": {{
      ""Calories"": ""800kcal""// here it's important that that format will be 800kcal, a number then kcal, if there is a range like 250-450kcal provide the average value that would be 350kcal,
      ""Proteins"": ""40g"" , //here it's important that that format will be 40g ,a number then g
      ""Carbohydrates"": ""75g"", //here it's important that that format will be 75g, a number then g
      ""Fats"": ""35g"", //here it's important that that format will be 35g, a number then g
    }},

Macronutrient Percentage: Provide the percentage of total calories for each macronutrient (carbohydrates, proteins, fats) , formatted as percentages. 
    So Please follow this format :
    ""Macronutrients_Pourcentage"": {{
      ""ProteinPercentage"": ""20.6%"", // here it's important that that format will be 20%, a number then %
      ""CarbsPercentage"": ""38.7%"",
      ""FatsPercentage"": ""40.6%"" 
    }},


Micronutrient: Provide a simple list of key micronutrients present in the meal, formatted as tags. Include only the names of these nutrients.

Serving Size: Add a tag for the serving size, indicating the quantity in grams of the final prepared dish.

Ingredient List for Groceries: List all the ingredients used in the recipe, without specifying quantities. This list will be used for generating grocery lists. add items even if they are optional.

and to make easier to parse and style meal recipes in the react app MealInformation object should contain the exact recipe of 
the meal but decomposed into elements.
	

This json representation will help us to divide the markdown recipe into its components while keeping exactly the same content in markdown format, 
write the content of each section without rewriting the title of the section plz
";

            // we generate the final json prompt with GPT 3.5
            var userMealDataBreakdownJson = await _openAIService.GenerateJsonBasedOnPromptResponseAsync(systemPromptJsonMealDataGeneration, userPromptJsonMealBreakdown, 4096);
            var MealDataBreakdownJson = JsonConvert.DeserializeObject<MealTotalBreakdown>(userMealDataBreakdownJson);


            meal.mealRecipeBreakdown = MealDataBreakdownJson!.MealInformation;
            meal.Macronutrients = MealDataBreakdownJson.MealDetails.Macronutrients;
            meal.Micronutrients = MealDataBreakdownJson.MealDetails.Micronutrients;
            meal.ServingSize = MealDataBreakdownJson.MealDetails.ServingSize;
            meal.Ingredients = MealDataBreakdownJson.MealDetails.Ingredients;
            meal.Macronutrients_Pourcentage = MealDataBreakdownJson.MealDetails.Macronutrients_Pourcentage;
            meal.MealBackgroundColor = GetRandomMealBgColor();

            // verify if meal.Macronutrients_Pourcentage are null

            if (meal.Macronutrients_Pourcentage is null)
            {
                var macroPourcentage = CalculateMacronutrientPercentagesFromString(meal.Macronutrients.Calories, meal.Macronutrients.Carbohydrates, meal.Macronutrients.Proteins, meal.Macronutrients.Fats);

                meal.Macronutrients_Pourcentage = new Macronutrients_Pourcentage
                {
                    CarbsPercentage = macroPourcentage.CarbsPercentage,
                    ProteinPercentage = macroPourcentage.ProteinPercentage,
                    FatsPercentage = macroPourcentage.FatsPercentage
                };
            }


        }

        private (string CarbsPercentage, string ProteinPercentage, string FatsPercentage) CalculateMacronutrientPercentagesFromString(
            string totalCaloriesStr, string carbsStr, string proteinStr, string fatsStr)
        {
            try
            {
                // Convert string values to double, extracting the numeric part
                double totalCalories = double.Parse(totalCaloriesStr.TrimEnd('k', 'c', 'a', 'l').Trim());
                double carbsGrams = double.Parse(carbsStr.TrimEnd('g').Trim());
                double proteinGrams = double.Parse(proteinStr.TrimEnd('g').Trim());
                double fatsGrams = double.Parse(fatsStr.TrimEnd('g').Trim());

                // Calories per gram for each macronutrient
                const double caloriesPerGramCarbs = 4.0;
                const double caloriesPerGramProtein = 4.0;
                const double caloriesPerGramFats = 9.0;

                // Calculate total calories from each macronutrient
                double caloriesFromCarbs = carbsGrams * caloriesPerGramCarbs;
                double caloriesFromProtein = proteinGrams * caloriesPerGramProtein;
                double caloriesFromFats = fatsGrams * caloriesPerGramFats;

                // Calculate the percentage of total calories for each macronutrient
                double carbsPercentage = caloriesFromCarbs / totalCalories * 100;
                double proteinPercentage = caloriesFromProtein / totalCalories * 100;
                double fatsPercentage = caloriesFromFats / totalCalories * 100;

                // Format and return the percentages as strings with two decimal places
                return ($"{carbsPercentage:F2}", $"{proteinPercentage:F2}", $"{fatsPercentage:F2}");
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error calculating macronutrient percentages: {ex.Message}");
                // make a quick prompt to fix it
                //throw new Exception("Error calculating macronutrient percentages");
                return ("Error", "Error", "Error");
            }
        }

        private async Task<string> GetMealRecipe(aMeal meal, string UserInputsJson)
        {

            string systemPrompt = $@"You are an AI assistant for MealGenius, an app designed for personalized nutrition and meal planning.
 
                                It focuses on setting nutritional goals and providing tailored meal plans based on user data. 
                                The app caters to a diverse audience, including individuals with ADHD, and emphasizes informative educative content while being friendly, fun.

                                MealGenius is used globally, so please use simple, clear English, avoiding slang or region-specific terms.
                                You can use emojis to add engagement and fun, but only where appropriate – do not overuse them.

                                User information relevant informations is provided in the following JSON format.
                                {UserInputsJson}";

            string userRecipeGenerationprompt = $@"Create a personalized and engaging recipe for this meal
{meal.ToString()}
Ensure the recipe is tailored to the user, with a friendly, chef-like tone, incorporating these specific elements:

## Introduction
	Begin with a warm, personalized greeting, mentioning the user's name and introducing the recipe.
	Recipe Name and Description: Clearly state the recipe name and provide an engaging description, highlighting why this meal is beneficial for the user.

## Ingredients
	Detail the ingredients for one serving  with easy-to-follow quantities. (specify the serving size in the end explicitly based on the ingredients),

## Serving Size
	based on the quantities of the ingredients Specify the serving size in grams for the final prepared dish, making it clear that this refers to the ready-to-serve meal.
    please follow this format in bullet points: 
    - 200g firm tofu, pressed and cubed
    - 1 stalk fresh lemongrass, finely chopped
    - 1 clove garlic, minced
    - 1 small piece ginger (about 2cm), grated

## Detailed Cooking Instructions
	specify each step, followed by a detailed, easy-to-follow explanation. Make the instructions engaging and motivating, encouraging users to enjoy the cooking process.
	please follow this format in bullet points: 
		- Step 1: detailed, easy-to-follow explanation for step 1
		- Step 2: detailed, easy-to-follow explanation for step 2
		- Step x: detailed, easy-to-follow explanation for step x, the more steps, the better
		- same for other steps...
        - The last step should be about Plating and the process of arranging and presenting food on the plate in an aesthetically pleasing manner.
## Appliances/Tools Needed
	based on the cooking instructions List the kitchen appliances and tools required to prepare the meal, ensuring users are well-prepared before starting.
	please follow this format in bullet points: 
		- Appliance/Tool 1
		- Appliance/Tool 2
		- Appliance/Tool 3
## Meal Timing Recommendations
	Include advice on the best time of day to enjoy this meal, and when it might be less ideal, based on its nutritional content.

## Macronutrients  Breakdown
	At the end of the recipe, provide a detailed breakdown of macronutrients (calories, carbohydrates, proteins, fats) This is placed last to ensure the language model has full context of the ingredients, quantities, and serving size for more accurate calculations.
	**Calories:** Total energy content of the meal, do not give a range specify an average of the total calories based on the ingredients, crucial for managing energy intake.
	**Carbohydrates:** calculate the quantity in grams, includes the types (e.g., simple vs. complex) 
	**Proteins:** calculate the quantity in grams
	**Fats:** calculate the quantity in grams, Describes the types of fats present (saturated, unsaturated).
	
## Key micronutrients
	Emphasizing each micronutrient(vitamins & minerals) and Fibers in the meal and in which ingredients it's presents and its health benefits and relevance to the user.
    specify titles of micronutrient in bold **Vitamie C:**
## Health Benefits
	This section offers a holistic view of the meal's nutritional profile, combining information on macronutrients, key micronutrients, and fibers. It showcases how each component contributes to the user's health and supports their health goals.

## Conclusion
	Conclude with a message that reinforces how this meal contributes to the user's health and enjoyment.

it's imporant to respect the format of the markdown that we specified for you SPECIALLY THE HEADERS ##, so it'll be easier for us to parse by our app

Markdown Format: Use Markdown for clear formatting, emphasizing important sections in bold.

Note for GPT : Important data and conclusions should be bolded for emphasis

Your goal is to create a recipe that is nutritionally informative, fun and easy to follow, and resonates personally with the user, inspiring them to confidently prepare and enjoy the meal.

Food is not just to nourish the body, Food nourishes the soul, You have to romance people, It has to be something that makes people go, omg, I can't wait to get a fork and dig into that

Use a conversational tone, as a chef is speaking directly to them, starting by greeting the user by their name.

Note for GPT : PLZ DIRECTLY START BY GENERATING THE MARKDOWN, !!!DO NOT write something before like ""---"" or ""```markdown""

Please Ensure that the markdown is similar to the specified format to make it easy for the react app the formar it

Start directly by the markdown header  : # The Title of the Recipe
";

            var chatRecipeResponse = await _openAIService.GetResponseAsync(systemPrompt, userRecipeGenerationprompt, OpenAI_API.Models.Model.GPT4_Turbo, 4095);

            return chatRecipeResponse;
        }

        private string GetRandomMealBgColor()
        {
            int randomIndex = random.Next(mealBackgroundcolors.Count);
            return mealBackgroundcolors[randomIndex];
        }
    }

}